version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      npm-dependencies:
        patterns: ["*"]
    labels:
      - dependencies
      - js

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: daily
    groups:
      cargo-dependencies:
        patterns: ["*"]
    labels:
      - dependencies
      - rust
